In [2]:
import numpy as np
import pandas as pd

# Soal 1

In [83]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
np.roll(arr,-1, axis=1)

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

# Soal 2

In [88]:
np.random.randn(6).reshape(3,2)

array([[ 0.92147024, -2.97736009],
       [ 0.57899052, -1.61439301],
       [-0.58502392,  0.88001427]])

# Soal 3

## Data

In [9]:
melb = pd.read_csv('./datasets/melb_data.csv')
melb.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [28]:
avg_price_4r  = melb[melb['Rooms'] == 4]['Price'].mean()
avg_price_4r

1445281.7358630951

# Soal 4

In [16]:
arr = np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13],[14,15,16,17]])
arr

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [26]:
arr[1:3,1:3]

array([[ 7,  8],
       [11, 12]])