In [1]:
import numpy as np
import pandas as pd

numpy --> n-dimensional array computation

pandas --> data format specifically designed for data analysis (Series dan DataFrame)

In [2]:
my_list = [10,20,30,1]
my_list2 = [40,50,60,2]
my_list3 = [70,80,90,3]

my_2d_list = [my_list, my_list2, my_list3]

this_array = np.array(my_2d_list)
this_array

array([[10, 20, 30,  1],
       [40, 50, 60,  2],
       [70, 80, 90,  3]])

how can we retrieve the elements in the 3rd column of hte array?

In [9]:
this_array[:, 2]

array([30, 60, 90])

how can we retrieve 90 from the array

In [10]:
this_array[2, 2]

90

how we can retreieve the 2nd element of 1st and 2nd row from the array

In [17]:
this_array[0:2,1]

array([20, 50])

what will happen if you substract the array with np.array([1,2,3])?

In [18]:
other_array = np.array([1,2,3])
this_array - other_array

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [19]:
this_array.shape

(3, 4)

syarat operasi aritmatik numpy array:
1. jumlah baris yang sama
2. atau jumlah kolom yang sama dengan yg sebelah kiri

In [20]:
other_array.reshape(3,1)

array([[1],
       [2],
       [3]])

In [21]:
this_array - other_array.reshape(3,1)

array([[ 9, 19, 29,  0],
       [38, 48, 58,  0],
       [67, 77, 87,  0]])

what will happen if you execute new_array = np.concatenate((this_array, [[4,5,6,7]], axis=1)?

In [30]:
new_array = np.concatenate(
    (this_array, [[4,5,6,7]]), axis=1
)

new_array

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [25]:
np.array([[4,5,6,7]]).shape

(1, 4)

jika mau nambah baris (axis=0) --> jumlah kolom di kiri = jumlah kolom di kanan

jika mau nambah baris (axis=1) --> jumlah baris di kiri = jumlah baris di kanan

---------------------

------------------------------

In [47]:
df_restaurants = pd.read_csv('./datasets/Top250.csv')
df_restaurants.head()

Rank   Restaurant                                            Content  \
0     1   McDonald's                                                NaN   
1     2    Starbucks                                                NaN   
2     3  Chick-fil-A  While Popeyes got a lot of the chicken buzz in...   
3     4    Taco Bell                                                NaN   
4     5  Burger King                                                NaN   

   Sales YOY_Sales  Units YOY_Units Headquarters             Segment_Category  
0  40412      4.9%  13846     -0.5%          NaN       Quick Service & Burger  
1  21380      8.6%  15049      3.0%          NaN  Quick Service & Coffee Cafe  
2  11320     13.0%   2470      5.0%          NaN      Quick Service & Chicken  
3  11293      9.0%   6766      2.7%          NaN      Quick Service & Mexican  
4  10204      2.7%   7346      0.2%          NaN       Quick Service & Burger

In [48]:
df_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Rank              250 non-null    int64 
 1   Restaurant        250 non-null    object
 2   Content           33 non-null     object
 3   Sales             250 non-null    int64 
 4   YOY_Sales         250 non-null    object
 5   Units             250 non-null    int64 
 6   YOY_Units         250 non-null    object
 7   Headquarters      52 non-null     object
 8   Segment_Category  250 non-null    object
dtypes: int64(3), object(6)
memory usage: 17.7+ KB


In [49]:
df_restaurants['YOY_Sales'][0].replace('%', '')

'4.9'

In [50]:
float(df_restaurants['YOY_Sales'][0].replace('%', ''))

4.9

In [51]:
# string to float

# define a regular function, then apply it ot every row
def convert_to_decimal(x):
    return float(x.replace('%', '')) / 100

df_restaurants['YOY_Sales'] = df_restaurants['YOY_Sales'].apply(convert_to_decimal)

In [52]:
df_restaurants['YOY_Units'] = df_restaurants['YOY_Units'].apply(lambda x: float(x.replace('%', '')) / 100)

In [53]:
df_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Rank              250 non-null    int64  
 1   Restaurant        250 non-null    object 
 2   Content           33 non-null     object 
 3   Sales             250 non-null    int64  
 4   YOY_Sales         250 non-null    float64
 5   Units             250 non-null    int64  
 6   YOY_Units         250 non-null    float64
 7   Headquarters      52 non-null     object 
 8   Segment_Category  250 non-null    object 
dtypes: float64(2), int64(3), object(4)
memory usage: 17.7+ KB


retrieve the namo of quick service & mexican restaurants that are in rank 1-50

In [57]:
df_restaurants[
    (df_restaurants['Segment_Category'] == 'Quick Service & Mexican')
    & (df_restaurants['Rank'].between(1,50))
]

Rank Restaurant Content  Sales  YOY_Sales  Units  YOY_Units Headquarters  \
3     4  Taco Bell     NaN  11293       0.09   6766      0.027          NaN   

          Segment_Category  
3  Quick Service & Mexican

retrieve top 20 quick service & burger restaurants based on their YOY Sales

In [60]:
df_restaurants[
    (df_restaurants['Segment_Category'] == 'Quick Service & Burger')
].sort_values(by='YOY_Sales', ascending=False)

Rank                     Restaurant  \
37    38                       Culver's   
29    30                    Whataburger   
0      1                     McDonald's   
12    13                 Sonic Drive-In   
49    50                In-N-Out Burger   
6      7                        Wendy's   
4      5                    Burger King   
75    76                   White Castle   
23    24                Jack in the Box   
84    85  Checkers Drive-In Restaurants   
42    43                     Carl's Jr.   
34    35                       Hardee's   
50    51                 Steak 'n Shake   

                                              Content  Sales  YOY_Sales  \
37  One of the country's fastest-growing chains ov...   1795      0.139   
29                                                NaN   2556      0.058   
0                                                 NaN  40412      0.049   
12  The drive-in chain grew same-store sales for t...   4687      0.046   
49                                                NaN    957      0.046   
6                                                 NaN   9762      0.042   
4                                                 NaN  10204      0.027   
75                                                NaN    579      0.024   
23                                                NaN   3504      0.011   
84                                                NaN    535     -0.018   
42                                                NaN   1423     -0.025   
34                                                NaN   2020     -0.040   
50  As of August, the chain had temporarily closed...    950     -0.077   

    Units  YOY_Units Headquarters        Segment_Category  
37    732      0.067          NaN  Quick Service & Burger  
29    830      0.006          NaN  Quick Service & Burger  
0   13846     -0.005          NaN  Quick Service & Burger  
12   3526     -0.021          NaN  Quick Service & Burger  
49    351      0.035          NaN  Quick Service & Burger  
6    5852      0.007          NaN  Quick Service & Burger  
4    7346      0.002          NaN  Quick Service & Burger  
75    371     -0.005          NaN  Quick Service & Burger  
23   2243      0.003          NaN  Quick Service & Burger  
84    584     -0.002          NaN  Quick Service & Burger  
42   1095     -0.023          NaN  Quick Service & Burger  
34   1820     -0.014          NaN  Quick Service & Burger  
50    576     -0.030          NaN  Quick Service & Burger

calculate the average sales in each restaurant headquarters

In [61]:
df_restaurants.groupby('Headquarters')['Sales'].mean()

Headquarters
Addison, TX             297.500000
Atlanta, GA             335.000000
Austin, TX              349.000000
Birmingham, AL          290.000000
Boston, MA              289.000000
Chattanooga, TN         275.000000
Cheyenne, WY            373.000000
Coppell, TX             410.000000
Countryside, IL         338.000000
Dallas, TX              398.333333
Denver, CO              289.000000
Doral, FL               340.000000
Dunwoody, GA            343.000000
Emeryville, CA          357.000000
Houston, TX             312.333333
Irvine, CA              265.000000
Irving, TX              325.333333
Lexington, KY           275.000000
Louisville, KY          404.000000
Miami, FL               425.000000
Minneapolis, MN         306.000000
Minnetonka, MN          329.000000
Mission Viejo, CA       259.000000
Nashville, TN           426.000000
New York, NY            281.000000
Oklahoma City, OK       268.000000
Orange City, IA         269.000000
Orlando, FL             253.000000
Pasaden