# Module 02

## Session 02 Python for Data Analysis

# Numpy Array

In [2]:
import numpy as np

## One Dimensional Array

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [7]:
type(my_list)

list

In [8]:
np.array(my_list)

array([1, 2, 3])

## Two Dimensional Array

In [9]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Three Dimesional Array

In [11]:
my_list3 = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]]
]
my_list3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
 [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

## Creating array (function)

### np.array()

In [12]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

### np.arange()

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### np.zeros()

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.ones()

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### np.eye()

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
np.random.rand(2)

array([0.20674464, 0.81278867])

In [24]:
np.random.rand(5,5)

array([[0.86822266, 0.82418133, 0.68640922, 0.07627267, 0.53639563],
       [0.19741578, 0.54225863, 0.66456985, 0.78541756, 0.27372202],
       [0.18532628, 0.35963773, 0.8781316 , 0.55591111, 0.41735345],
       [0.08098853, 0.02808488, 0.58995472, 0.95962011, 0.6470085 ],
       [0.90554787, 0.36132464, 0.68709188, 0.82622618, 0.69627242]])

In [25]:
np.random.randn(2)

array([ 0.45753479, -0.32196867])

In [26]:
np.random.randn(5,5)

array([[-0.34808167,  0.67135708,  2.25020611, -0.28147228, -0.43180641],
       [-1.08393169, -1.49121926,  0.82494344,  0.26464652, -1.1192067 ],
       [-0.25910777, -0.49354867, -0.61227902,  0.16934824,  0.43952608],
       [-0.7531362 ,  0.27155125,  1.79031969,  0.64981133, -1.06127533],
       [-1.33831839, -1.17172474,  0.38122301,  0.22742301,  0.8257767 ]])

In [27]:
np.random.randint(1,100)

61

In [28]:
np.random.randint(1,100,10)

array([54, 34, 23, 34, 66, 88, 95, 74, 95, 22])

## Array Shape

In [32]:
array_1d = np.array(my_list)
array_2d = np.array(my_matrix)
array_3d = np.array(my_list3)

In [33]:
array_1d

array([1, 2, 3])

In [34]:
array_1d.shape

(3,)

In [35]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array_2d.shape

(3, 3)

In [37]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [38]:
array_3d.shape

(3, 3, 3)

## Reshaping array

In [39]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.shape

(25,)

In [41]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [43]:
arr.reshape(1,25).shape

(1, 25)

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [47]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [49]:
array_2d.reshape(-1).shape

(9,)

In [50]:
array_3d.reshape(-1).shape

(27,)

## Min & Max

In [51]:
randarr = np.random.randint(1,50,10)
randarr

array([15, 17, 37,  7,  7, 15, 21, 26,  6, 36])

In [52]:
randarr.max()

37

In [53]:
randarr.argmax()

2

In [54]:
randarr.min()

6

In [55]:
randarr.argmax()

2