# Module 02

## Session 02 Python for Data Analysis

# Numpy Indexing & Selection

In [1]:
import numpy as np

## Selection

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

## Multiple Selection (Slicing)

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Selection on 2D Array

In [16]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1]

array([20, 25, 30])

In [18]:
arr_2d[1][0]

20

In [19]:
arr_2d[1,0]

20

In [20]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
arr_2d[:,2]

array([15, 30, 45])

## Fancy Indexing

In [23]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
[arr[2], arr[5], arr[9]]

[2, 5, 9]

In [25]:
arr[[2,5,9]]

array([2, 5, 9])

In [26]:
arr[[9,2,5]]

array([9, 2, 5])

In [27]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [28]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [29]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])